# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef58d712aa310b8fe5e186b7552605bebd4f8943f9a846753fcc43b1f0311c5013b08b480198069a21c90ac6af93b85d7a73d81330ea4c096fbb5bb05850c94

test:
  secret_key_base: 529a4064d36aa4cb6697c3f16a60b8d0b1cca14864d39b294d574703da68ef4a6ada2da5c0eb3802f53f4306a23230a333d167f14faa1365cba93c50795c3b3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
